name: cenv
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.7.0
  - astor=0.7.1
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.56.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=0.8
  - intel-openmp=2019.3
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - joblib=0.13.2
  - jpeg=9b
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.36
  - libprotobuf=3.7.1
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=2.6.11
  - matplotlib=3.0.3
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - mock=2.0.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - pandas=0.24.2
  - parso=0.3.4
  - path.py=12.0.1
  - patsy=0.5.1
  - pbr=5.1.3
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - prompt_toolkit=2.0.9
  - protobuf=3.7.1
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch=1.0.1
  - pytz=2019.1
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - tensorboard=1.13.1
  - tensorboardx=1.6
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.8
  - torchvision=0.2.2
  - tornado=6.0.2
  - tqdm=4.31.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - werkzeug=0.15.2
  - wheel=0.33.1
  - xz=5.2.4
  - zipp=0.3.3
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - atari-py==0.1.7
    - attrs==19.1.0
    - awscli==1.16.144
    - azure==1.0.3
    - azure-common==1.1.20
    - azure-mgmt==0.20.2
    - azure-mgmt-common==0.20.0
    - azure-mgmt-compute==0.20.1
    - azure-mgmt-network==0.20.1
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-resource==0.20.1
    - azure-mgmt-storage==0.20.0
    - azure-nspkg==3.0.2
    - azure-servicebus==0.20.1
    - azure-servicemanagement-legacy==0.20.2
    - azure-storage==0.20.3
    - bleach==3.1.0
    - boto3==1.9.134
    - botocore==1.12.134
    - box2d-py==2.3.8
    - cached-property==1.5.1
    - chainer==1.18.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==0.8.1
    - colorama==0.3.9
    - coverage==5.0a4
    - cython==0.29.7
    - defusedxml==0.6.0
    - dill==0.2.9
    - docutils==0.14
    - entrypoints==0.3
    - enum34==1.1.6
    - filelock==3.0.10
    - future==0.17.1
    - glfw==1.7.1
    - idna==2.8
    - imageio==2.5.0
    - ipykernel==5.1.0
    - ipywidgets==7.4.2
    - jinja2==2.10.1
    - jmespath==0.9.4
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - lasagne==0.1
    - line-profiler==2.1.2
    - lockfile==0.12.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mpi4py==3.0.1
    - msgpack-python==0.5.6
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - nose==1.3.7
    - nose2==0.9.1
    - notebook==5.7.8
    - opencv-python==4.1.0.25
    - plotly==3.8.1
    - prettytensor==0.7.4
    - progressbar2==3.39.3
    - pyasn1==0.4.5
    - pyglet==1.3.2
    - pyopengl==3.1.3b2
    - pyprind==2.11.2
    - pyrsistent==0.14.11
    - python-utils==2.3.0
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - redis==3.2.1
    - requests==2.21.0
    - rllab==0.0.1.dev0
    - rsa==3.4.2
    - s3transfer==0.2.0
    - send2trash==1.5.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tfmpl==1.0.2
    - theano==1.0.4
    - urllib3==1.24.1
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
    - zmq==0.0.0
